In [ ]:
import pandas as pd
import numpy as np
import collections

In [ ]:
df = pd.read_csv('inputs/input10.txt', delim_whitespace=True, header=None)
df.columns = ['val']
vals = df['val'].to_numpy()
vals

array([ 30,  73,  84, 136, 132, 117,  65, 161,  49,  68, 139,  46,  21,
       127, 109, 153, 163, 160,  18,  22, 131, 146,  62, 113, 172, 150,
       171,  98,  93, 130, 170,  59,   1, 110,   2,  55,  37,  44, 148,
       102,  40,  28,  35,  43,  56, 169,  33,   5, 141,  83,  15, 105,
       142,  36, 116,  11,  45,  82,  10,  17, 159, 140,  12, 108,  29,
        72, 121,  52,  91, 166,  88,  97, 118,  99, 124, 149,  16,   9,
       143, 104,  57,  79, 123,  58,  96,  24, 162,  23,  92,  69, 147,
       156,  25, 133,  34,   8,  85,  76, 103, 122])

In [ ]:
builtin = max(vals) + 3
builtin

175

In [ ]:
vals = np.append(vals, builtin)
vals = np.append(vals, 0)

In [ ]:
v = np.sort(vals)
v

array([  0,   1,   2,   5,   8,   9,  10,  11,  12,  15,  16,  17,  18,
        21,  22,  23,  24,  25,  28,  29,  30,  33,  34,  35,  36,  37,
        40,  43,  44,  45,  46,  49,  52,  55,  56,  57,  58,  59,  62,
        65,  68,  69,  72,  73,  76,  79,  82,  83,  84,  85,  88,  91,
        92,  93,  96,  97,  98,  99, 102, 103, 104, 105, 108, 109, 110,
       113, 116, 117, 118, 121, 122, 123, 124, 127, 130, 131, 132, 133,
       136, 139, 140, 141, 142, 143, 146, 147, 148, 149, 150, 153, 156,
       159, 160, 161, 162, 163, 166, 169, 170, 171, 172, 175])

In [ ]:
collections.Counter([(v[i+1]-v[i]) for i in range(len(v)-1)])

Counter({1: 64, 3: 37})

In [ ]:
64*37

2368

In [ ]:
#Part 2
df = pd.read_csv('inputs/input10.txt', delim_whitespace=True, header=None)
df.columns = ['val']
vals = df['val'].to_numpy()

builtin = max(vals) + 3

vals = np.append(vals, builtin)
vals = np.append(vals, 0)
v = np.sort(vals)
v

array([  0,   1,   2,   5,   8,   9,  10,  11,  12,  15,  16,  17,  18,
        21,  22,  23,  24,  25,  28,  29,  30,  33,  34,  35,  36,  37,
        40,  43,  44,  45,  46,  49,  52,  55,  56,  57,  58,  59,  62,
        65,  68,  69,  72,  73,  76,  79,  82,  83,  84,  85,  88,  91,
        92,  93,  96,  97,  98,  99, 102, 103, 104, 105, 108, 109, 110,
       113, 116, 117, 118, 121, 122, 123, 124, 127, 130, 131, 132, 133,
       136, 139, 140, 141, 142, 143, 146, 147, 148, 149, 150, 153, 156,
       159, 160, 161, 162, 163, 166, 169, 170, 171, 172, 175])

In [ ]:
#Sharon
diff = [str(v[elem]-v[elem-1]) for elem in range(1, len(v))]
diff = ''.join(diff).split('3')

total = 1

for i in diff:
    if len(i)==2:
        total*=2
    if len(i)==3:
        total*=4
    if len(i)==4:
        total *=7

total

1727094849536