In [78]:
import numpy as np
import pandas as pd
import copy

In [143]:
filename = 'inputs/input11.txt'
f = open(filename).read()
f.split('\n')


['LLLLLLLLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLL.LLLLLLL.LLLLLL.LLLLLLLL.LLLLL.LLLLLLLL..LLLLLLLLL',
 'LLLLLLLLL.LLLL.LLLLL.L.LLLLLLL.LLLLLLLLL.LLLLLL.L.LLLLLL.LLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLL',
 'LLLLLLLLL..LLL.LLLLL.LLLLLLLLL.LLLLLLLL..LLLLLLLL..LLLLL.LLLLL.LLLLLLLLLLLLLLLLLLL.LLL.L.LLLLLLLLL',
 'LLLLLLLLL.LLLL.LLLLLLLLLLLLLLL.LLLLLLLLL.LLLLLLLL.LLLLLL.LLLLLL.LLLLLLLLLLLLLL...LLLLL.LLLLLLLLL.L',
 'LLLLLLLLL.LLLLLLLLLL.LLLLLLL.L.LLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLL.LLLLLLLL.LLLLLLL.L.LLL.L.LLLL.LLLL',
 'LLLLLLLLLLLLLLLLLLLLLLLLLLL.LL.LLLLLLLLLLL.LLLLLL.LLLLLL.LLLLLL.LLLL.LLL..LLLLLL.LLLLLLL.LLLLLLLLL',
 'LLLLLLLLLLLLLLLLLLLL.LLL.LLLLL.LLLLLLLLL.LLLL.LLLLLL..L..LLLLLLLLLLLL.LL.LLLLLLLLLLLLLLL.LLLLLL.LL',
 'L....L.....L..L...................L.....L..L..L..L...LL....LL....L...........L.L.L..LL.L..LL..L...',
 'LLLLLLLLL.LL.L.LLLLL.LLLLLLLLLLLLLLLLL.L.LLLLLLLL.LLLLLL.LLLLLL.LLLLLLLLLLLLLLLL..LLLLLL.LLLLLLLLL',
 'LLLLLL.LL.LLLL.LLLLL.LLLLLLLLLLL.LLLLLLL.LLLLLLLLLLLLLLL.LLLLLL.LLLLL.L

In [144]:
rows = len(f.split('\n')[0])
cols = len(f.split('\n'))

arr = np.array([int(i.replace('L','0').replace('.','-1').replace('#','1')) for i in f if i != '\n']).reshape(rows,cols)
arr

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [-1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [42]:
arr.shape

(10, 10)

In [43]:
def seat_changes1(orig_array, count=0):
    rows = orig_array.shape[0]
    cols = orig_array.shape[1]
    
    s = (rows, cols)
    next_arr = np.zeros(s, dtype=int)

    for r in range(rows):
        for c in range(cols):      

            sumAround = 0
            for nr in [r-1, r, r+1]:            
                for nc in [c-1, c, c+1]:                
                    if 0 <= nr <= rows-1 and 0 <= nc <= cols-1 and not(nr == r and nc == c):
                        #print('new:', nr, nc)
                        if orig_array[nr][nc] != -1:
                            sumAround += orig_array[nr][nc]
            #print('cell:', r, c, 'val:', orig_array[r][c], 'Sum:', sumAround)

            if orig_array[r][c] == 0 and sumAround == 0:
                next_arr[r][c] = 1
            elif orig_array[r][c] == 1 and sumAround >= 4:
                next_arr[r][c] = 0
            else:
                next_arr[r][c] = orig_array[r][c]
    count = count + 1
    if not np.array_equal(next_arr, orig_array):
        print(next_arr, count)        
        return seat_changes1(next_arr.copy(), count)
    else:
        print('Done')
        print(next_arr, count)
        return next_arr.copy()

In [44]:
seat_changes1(arr)


[[ 1 -1  0  0 -1  0  1 -1  1  1]
 [ 1  0  0  0  0  0  0 -1  0  1]
 [ 0 -1  0 -1  0 -1 -1  0 -1 -1]
 [ 1  0  0  0 -1  0  0 -1  0  1]
 [ 1 -1  0  0 -1  0  0 -1  0  0]
 [ 1 -1  0  0  0  0  1 -1  1  1]
 [-1 -1  0 -1  0 -1 -1 -1 -1 -1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1 -1  0  0  0  0  0  0 -1  0]
 [ 1 -1  1  0  0  0  0 -1  1  1]] 1
[[ 1 -1  1  1 -1  0  1 -1  1  1]
 [ 1  0  1  1  1  0  0 -1  0  1]
 [ 0 -1  1 -1  1 -1 -1  1 -1 -1]
 [ 1  0  1  1 -1  1  1 -1  0  1]
 [ 1 -1  1  1 -1  0  0 -1  0  0]
 [ 1 -1  1  1  1  0  1 -1  1  1]
 [-1 -1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  0  1  1  1  1  1  1  0  1]
 [ 1 -1  0  0  1  1  1  0 -1  0]
 [ 1 -1  1  0  1  1  1 -1  1  1]] 2
[[ 1 -1  1  0 -1  0  1 -1  1  1]
 [ 1  0  0  0  1  0  0 -1  0  1]
 [ 0 -1  0 -1  0 -1 -1  1 -1 -1]
 [ 1  0  0  0 -1  1  1 -1  0  1]
 [ 1 -1  0  0 -1  0  0 -1  0  0]
 [ 1 -1  0  0  1  0  1 -1  1  1]
 [-1 -1  0 -1  0 -1 -1 -1 -1 -1]
 [ 1  0  1  0  0  0  0  1  0  1]
 [ 1 -1  0  0  0  0  0  0 -1  0]
 [ 1 -1  1  0  1  0  1 -1  1  1]] 3
[

array([[ 1, -1,  1,  0, -1,  0,  1, -1,  1,  1],
       [ 1,  0,  0,  0,  1,  0,  0, -1,  0,  1],
       [ 0, -1,  1, -1,  0, -1, -1,  1, -1, -1],
       [ 1,  0,  1,  1, -1,  1,  1, -1,  0,  1],
       [ 1, -1,  1,  0, -1,  0,  0, -1,  0,  0],
       [ 1, -1,  1,  0,  1,  0,  1, -1,  1,  1],
       [-1, -1,  0, -1,  0, -1, -1, -1, -1, -1],
       [ 1,  0,  1,  0,  1,  1,  0,  1,  0,  1],
       [ 1, -1,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 1, -1,  1,  0,  1,  0,  1, -1,  1,  1]])

In [45]:
# https://stackoverflow.com/questions/28663856/how-to-count-the-occurrence-of-certain-item-in-an-ndarray
unique, counts = np.unique(seat_changes1(arr), return_counts=True)
dict(zip(unique, counts))

[[ 1 -1  0  0 -1  0  1 -1  1  1]
 [ 1  0  0  0  0  0  0 -1  0  1]
 [ 0 -1  0 -1  0 -1 -1  0 -1 -1]
 [ 1  0  0  0 -1  0  0 -1  0  1]
 [ 1 -1  0  0 -1  0  0 -1  0  0]
 [ 1 -1  0  0  0  0  1 -1  1  1]
 [-1 -1  0 -1  0 -1 -1 -1 -1 -1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 1 -1  0  0  0  0  0  0 -1  0]
 [ 1 -1  1  0  0  0  0 -1  1  1]] 1
[[ 1 -1  1  1 -1  0  1 -1  1  1]
 [ 1  0  1  1  1  0  0 -1  0  1]
 [ 0 -1  1 -1  1 -1 -1  1 -1 -1]
 [ 1  0  1  1 -1  1  1 -1  0  1]
 [ 1 -1  1  1 -1  0  0 -1  0  0]
 [ 1 -1  1  1  1  0  1 -1  1  1]
 [-1 -1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  0  1  1  1  1  1  1  0  1]
 [ 1 -1  0  0  1  1  1  0 -1  0]
 [ 1 -1  1  0  1  1  1 -1  1  1]] 2
[[ 1 -1  1  0 -1  0  1 -1  1  1]
 [ 1  0  0  0  1  0  0 -1  0  1]
 [ 0 -1  0 -1  0 -1 -1  1 -1 -1]
 [ 1  0  0  0 -1  1  1 -1  0  1]
 [ 1 -1  0  0 -1  0  0 -1  0  0]
 [ 1 -1  0  0  1  0  1 -1  1  1]
 [-1 -1  0 -1  0 -1 -1 -1 -1 -1]
 [ 1  0  1  0  0  0  0  1  0  1]
 [ 1 -1  0  0  0  0  0  0 -1  0]
 [ 1 -1  1  0  1  0  1 -1  1  1]] 3
[

{-1: 29, 0: 34, 1: 37}

In [46]:
# part 2
arr

array([[ 1, -1,  1,  1, -1,  1,  1, -1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1, -1,  1,  1],
       [ 1, -1,  1, -1,  1, -1, -1,  1, -1, -1],
       [ 1,  1,  1,  1, -1,  1,  1, -1,  1,  1],
       [ 1, -1,  1,  1, -1,  1,  1, -1,  1,  1],
       [ 1, -1,  1,  1,  1,  1,  1, -1,  1,  1],
       [-1, -1,  1, -1,  1, -1, -1, -1, -1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1,  1,  1,  1,  1,  1, -1,  1],
       [ 1, -1,  1,  1,  1,  1,  1, -1,  1,  1]])

In [47]:
arr[0:3,1]

array([-1,  1, -1])

In [48]:
list(range(2,3))

[2]

In [49]:
np.diagonal(arr, offset=1)

array([-1,  1, -1, -1,  1,  1, -1,  1,  1])

In [148]:
def seat_changes2(orig_array, count=0):
    rows = orig_array.shape[0]
    cols = orig_array.shape[1]
    s = (rows, cols)
    next_arr = np.zeros(s, dtype=int)

    for r in range(rows):
        for c in range(cols):

            sumAround = 0                    
            
            #row ahead:
            arr_part = orig_array[r, min(c+1, cols):cols] 
            #print('ahead', arr_part)
            # remove floor seats
            arr_part = arr_part[arr_part != -1]            
            if arr_part.size != 0:
                sumAround += arr_part.take(0)
                #print('ahead-first', arr_part.take(0))
            

            #row behind:
            arr_part = orig_array[r, 0:max(c, 0)]            
            #print('behind', arr_part)
            # remove floor seats
            arr_part = arr_part[arr_part != -1]
            if arr_part.size != 0:
                sumAround += arr_part.take(-1)
                #print('behind-last', arr_part.take(-1))
                

            #col up:
            arr_part = orig_array[0:max(r,0), c]            
            #print('up', arr_part)
            # remove floor seats
            arr_part = arr_part[arr_part != -1]
            if arr_part.size != 0:
                sumAround += arr_part.take(-1)
                #print('up-last', arr_part.take(-1))
                

            #col down:
            arr_part = orig_array[min(r+1, rows):rows, c]            
            #print('down', arr_part)
            # remove floor seats
            arr_part = arr_part[arr_part != -1]
            if arr_part.size != 0:
                sumAround += arr_part.take(0)
                #print('down-first', arr_part.take(0)) 
                

            #diag top left to bot right:
            ofst = c-r
            arr_part = np.diagonal(orig_array, offset=ofst)
            #print('diag1', arr_part)
            if ofst >= 0:

                temp_arr_part = arr_part[0:r].copy()
                #print('+diag1up', temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]             

                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(-1)
                    #print('+diag1up-last', temp_arr_part.take(-1)) 
                
                
                temp_arr_part = arr_part[min(r+1, len(arr_part)):len(arr_part)].copy()
                #print('+diag1down', temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]                

                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(0)
                    #print('+diag1down-first', temp_arr_part.take(0)) 
                

            else:
                temp_arr_part = arr_part[0:r+ofst].copy()                
                #print('-diag1up',r, ofst, temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]
                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(-1)
                    #print('-diag1up-last', temp_arr_part.take(-1))  
                
                temp_arr_part = arr_part[min(r+ofst+1, len(arr_part)):len(arr_part)]
                #print('-diag1down', r, ofst, temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]
                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(0)
                    #print('-diag1down-first', temp_arr_part.take(0)) 
                

            

            c = c
            flip_r = copy.deepcopy(r)
            r = (np.shape(orig_array)[0]-1)-r
            
            #diag bot left to top right:
            ofst = c-r
            arr_part = np.diagonal(np.flipud(orig_array), offset=ofst)
            #print('diag2', arr_part)
            if ofst >= 0:

                temp_arr_part = arr_part[0:r].copy()
                #print('+diag2up', temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]             

                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(-1)
                    #print('+diag2up-last', temp_arr_part.take(-1)) 
                
                
                temp_arr_part = arr_part[min(r+1, len(arr_part)):len(arr_part)].copy()
                #print('+diag2down', temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]                

                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(0)
                    #print('+diag2down-first', temp_arr_part.take(0)) 
                

            else:
                temp_arr_part = arr_part[0:r+ofst].copy()                
                #print('-diag2up',r, ofst, temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]
                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(-1)
                    #print('-diag2up-last', temp_arr_part.take(-1))  
                
                temp_arr_part = arr_part[min(r+ofst+1, len(arr_part)):len(arr_part)]
                #print('-diag2down', r, ofst, temp_arr_part)
                # remove floor seats
                temp_arr_part = temp_arr_part[temp_arr_part != -1]
                if temp_arr_part.size != 0:
                    sumAround += temp_arr_part.take(0)
                    #print('-diag2down-first', temp_arr_part.take(0)) 

            
            r = flip_r

            #print('cell:', r, c, 'val:', orig_array[r][c], 'Sum:', sumAround)

            if orig_array[r][c] == 0 and sumAround == 0:
                next_arr[r][c] = 1
            elif orig_array[r][c] == 1 and sumAround >= 5:
                next_arr[r][c] = 0
            else:
                next_arr[r][c] = orig_array[r][c]
    count = count + 1

    if not np.array_equal(next_arr, orig_array):
        #print(next_arr, count)
        #unique, counts = np.unique(next_arr, return_counts=True)
        #part_dict = dict(zip(unique, counts))
        #print(part_dict)
        print(count)        
        return seat_changes2(next_arr.copy(), count)
    else:
        print('Done')
        print(next_arr, count)
        unique, counts = np.unique(next_arr, return_counts=True)
        part_dict = dict(zip(unique, counts))
        print(part_dict)  
        return next_arr.copy()

In [149]:
seat_changes2(arr)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
Done
[[ 1  0  1 ...  1  0  1]
 [ 0  0  0 ...  0  0  0]
 [ 1  0  1 ...  1  0  1]
 ...
 [ 0  1  0 ...  1  0  1]
 [-1  0  0 ...  0  0  0]
 [ 1  1  0 ...  1  0  1]] 88
{-1: 1862, 0: 5528, 1: 2214}


array([[ 1,  0,  1, ...,  1,  0,  1],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  1, ...,  1,  0,  1],
       ...,
       [ 0,  1,  0, ...,  1,  0,  1],
       [-1,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  0, ...,  1,  0,  1]])

In [139]:
arr

array([[ 1, -1,  0,  0, -1,  0,  0, -1,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0, -1,  0,  0],
       [ 0, -1,  0, -1,  0, -1, -1,  0, -1, -1],
       [ 0,  0,  0,  0, -1,  0,  0, -1,  0,  0],
       [ 0, -1,  0,  0, -1,  0,  0, -1,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0, -1,  0,  0],
       [-1, -1,  0, -1,  0, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 1, -1,  0,  0,  0,  0,  0,  0, -1,  0],
       [ 1, -1,  0,  0,  0,  0,  0, -1,  0,  1]])

In [16]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
np.flipud(a)

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [23]:
np.flipud(a).diagonal(offset=1)

array([21, 17, 13,  9])

In [145]:
unique, counts = np.unique(seat_changes2(arr), return_counts=True)
dict(zip(unique, counts))

ahead-first 0
behind [ 0  0  0  0  0  0  0 -1  0 -1  0  0  0  0 -1 -1  0  0  0  0  0  0  0  0
  0  0 -1  0  0  0 -1]
behind-last 0
up [ 0  0  0  0  0  0  0 -1  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0 -1
  0  0  0  0  0 -1  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0 -1  0  0  0  0  0 -1  0  0]
up-last 0
down [ 0 -1  0  0  0  0 -1  0  0  0  0 -1 -1  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0 -1  0  0  0]
down-first 0
diag1 [ 0  0 -1  0  0  0  0  0  0 -1  0 -1  0 -1  0 -1  0  0  0  0 -1  0  0 -1
  0 -1  0  0 -1  0 -1  0  0 -1  0  0  0  0 -1  0 -1  0  0 -1  0 -1  0  0
  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0]
-diag1up 64 -33 [ 0  0 -1  0  0  0  0  0  0 -1  0 -1  0 -1  0 -1  0  0  0  0 -1  0  0 -1
  0 -1  0  0 -1  0 -1]
-diag1up-last 0
-diag1down 64 -33 [ 0 -1  0  0  0  0 -1  0 -1  0  0 -1  0 -1  0  0  0 -1  0  0  0  0  0  0
  0  0  0  0  0  0  0 -1  0]
-diag1down-first 0
diag2 [ 0  0  1  0  0  0  0  0  0 -1  0 -1  0  0 -1  0  0  0 -1  0  

KeyboardInterrupt: 